name: Build Plugin Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increment Plugin Version
        run: |
          FILE="src/coopleo.php"
          echo "IncrÃ©mentation de la version dans $FILE"
          VERSION_LINE=$(grep "Version:" $FILE)
          echo "Ligne de version actuelle: $VERSION_LINE"
          VERSION=$(echo "$VERSION_LINE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Version actuelle: $VERSION"
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Nouvelle version: $NEW_VERSION"
          sed -i "s/$VERSION/$NEW_VERSION/" $FILE
          grep "Version:" $FILE
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated Version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/coopleo.php
          git commit -m "Bump plugin version to $VERSION"
          git push

      - name: Prepare Plugin Directory
        run: |
          mkdir -p build/coopleo
          cp -r src/* build/coopleo/
          rm -rf build/coopleo/.git build/coopleo/.github

      - name: Zip Plugin
        run: |
          cd build && zip -r coopleo.zip coopleo
          mv coopleo.zip ../plugin.zip

      - name: Upload Release
        env:
          API_URL: "https://plugin-manager.atomikagency.fr"
        run: |
          echo "Upload du fichier plugin.zip avec la version $VERSION"

          curl -X POST \
            -F "plugin_id=0f99c4e7-15b6-4fe9-abf1-8742c8fce3de" \
            -F "zip_file=@plugin.zip" \
            -F "version=$VERSION" \
            $API_URL/api/releases
